runtime: nodejs
env: flex
service: hull-processor
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
health_check:
  enable_health_check: True
  check_interval_sec: 10
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
