# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: node:10.16
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1_dependencies_{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1_dependencies_

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1_dependencies_{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
      # - run: npm i --no-save --no-cache hull-connector-tester@latest && ./node_modules/.bin/hull-connector-tester
